import { ExamTemplate } from "@/types/paper";

export const DEFAULT_TEMPLATES: ExamTemplate[] = [
  {
    id: "tpl_board_exam",
    name: "CBSE / State Board Examination",
    description: "Standard 3-hour board exam template with Sections A through E, objective questions, short and long answer types.",
    category: "Board Exam",
    header: {
      institutionName: "CENTRAL BOARD OF SECONDARY EDUCATION",
      examName: "ALL INDIA SENIOR SCHOOL CERTIFICATE EXAMINATION",
      durationMinutes: 180,
      totalMarks: 70,
      generalInstructions: [
        "This question paper contains 33 questions across 5 sections.",
        "Section A contains 16 multiple-choice questions carrying 1 mark each.",
        "Section B contains 5 very short answer questions carrying 2 marks each.",
        "Section C contains 7 short answer questions carrying 3 marks each.",
        "Section D contains 2 case-based questions carrying 4 marks each.",
        "Section E contains 3 long answer questions carrying 5 marks each.",
        "All questions are compulsory. Internal choice is provided in some questions.",
        "Use of log tables and calculators is not permitted.",
      ],
    },
    styling: {
      paperSize: "A4",
      fontFamily: "Times New Roman",
      fontSize: 11,
      lineHeight: 1.4,
      margins: { top: 15, bottom: 15, left: 18, right: 18 },
      watermark: { enabled: false, text: "CONFIDENTIAL", opacity: 0.08, fontSize: 48, rotation: -45 },
    },
    defaultInstructions: [
      "Check that this question paper contains 8 printed pages.",
      "15 minutes reading time has been allotted to read this paper.",
    ],
    sectionStructure: [
      { title: "SECTION A", instructions: "Multiple Choice Questions (1 Mark each)", defaultQuestionType: "mcq", defaultMarksPerQuestion: 1, questionCount: 16 },
      { title: "SECTION B", instructions: "Very Short Answer Questions (2 Marks each)", defaultQuestionType: "very_short_answer", defaultMarksPerQuestion: 2, questionCount: 5 },
      { title: "SECTION C", instructions: "Short Answer Questions (3 Marks each)", defaultQuestionType: "short_answer", defaultMarksPerQuestion: 3, questionCount: 7 },
      { title: "SECTION D", instructions: "Case-based Questions (4 Marks each)", defaultQuestionType: "case_study", defaultMarksPerQuestion: 4, questionCount: 2 },
      { title: "SECTION E", instructions: "Long Answer Questions (5 Marks each)", defaultQuestionType: "long_answer", defaultMarksPerQuestion: 5, questionCount: 3 },
    ],
  },
  {
    id: "tpl_college_semester",
    name: "College / University Semester Exam",
    description: "Standard university examination paper with Part A (Compulsory short questions) and Part B (Essay/analytical questions with internal choices).",
    category: "College/University",
    header: {
      institutionName: "DEPARTMENT OF HIGHER EDUCATION & RESEARCH",
      examName: "END SEMESTER DEGREE EXAMINATIONS",
      durationMinutes: 180,
      totalMarks: 100,
      generalInstructions: [
        "Answer ALL questions from Part A and any FIVE questions from Part B.",
        "Answers must be supported with relevant diagrams, equations, and derivations wherever applicable.",
        "Programmable calculators are strictly prohibited.",
      ],
    },
    styling: {
      paperSize: "A4",
      fontFamily: "Georgia",
      fontSize: 11.5,
      lineHeight: 1.45,
      margins: { top: 16, bottom: 16, left: 20, right: 20 },
      watermark: { enabled: false, text: "EXAMINATION", opacity: 0.06, fontSize: 44, rotation: -40 },
    },
    defaultInstructions: [],
    sectionStructure: [
      { title: "PART A", instructions: "Short Answer Questions (Answer all questions - 10 x 2 = 20 Marks)", defaultQuestionType: "short_answer", defaultMarksPerQuestion: 2, questionCount: 10 },
      { title: "PART B", instructions: "Analytical / Essay Questions (5 x 16 = 80 Marks)", defaultQuestionType: "long_answer", defaultMarksPerQuestion: 16, questionCount: 5 },
    ],
  },
  {
    id: "tpl_school_unit_test",
    name: "School Unit Test / Class Assessment",
    description: "Compact 45-minute to 1-hour test paper suitable for weekly or monthly unit reviews.",
    category: "School",
    header: {
      institutionName: "DELHI PUBLIC ACADEMY",
      examName: "MONTHLY UNIT EVALUATION TEST",
      durationMinutes: 60,
      totalMarks: 25,
      generalInstructions: [
        "All questions are compulsory.",
        "Marks are indicated against each question.",
        "Write answers neatly in the space provided.",
      ],
    },
    styling: {
      paperSize: "A4",
      fontFamily: "Inter",
      fontSize: 11,
      lineHeight: 1.35,
      margins: { top: 14, bottom: 14, left: 16, right: 16 },
      watermark: { enabled: false, text: "UNIT TEST", opacity: 0.08, fontSize: 36, rotation: -30 },
    },
    defaultInstructions: [],
    sectionStructure: [
      { title: "SECTION A", instructions: "Multiple Choice Questions (5 Marks)", defaultQuestionType: "mcq", defaultMarksPerQuestion: 1, questionCount: 5 },
      { title: "SECTION B", instructions: "Short Answer Questions (10 Marks)", defaultQuestionType: "short_answer", defaultMarksPerQuestion: 2, questionCount: 5 },
      { title: "SECTION C", instructions: "Long Answer / Problem Solving (10 Marks)", defaultQuestionType: "long_answer", defaultMarksPerQuestion: 5, questionCount: 2 },
    ],
  },
  {
    id: "tpl_competitive_exam",
    name: "Competitive / Entrance Exam (JEE / NEET style)",
    description: "Multiple choice format with single correct options, numerical response section, and negative marking advisory.",
    category: "Competitive Exam",
    header: {
      institutionName: "NATIONAL TESTING AGENCY (PRACTICE)",
      examName: "ALL INDIA JOINT ENTRANCE MOCK EXAMINATION",
      durationMinutes: 180,
      totalMarks: 300,
      generalInstructions: [
        "The test contains 75 questions in total (25 Physics, 25 Chemistry, 25 Mathematics).",
        "Each correct answer carries +4 marks. Each incorrect answer carries -1 mark.",
        "Unanswered questions carry 0 marks.",
      ],
    },
    styling: {
      paperSize: "A4",
      fontFamily: "Arial",
      fontSize: 10.5,
      lineHeight: 1.3,
      margins: { top: 12, bottom: 12, left: 14, right: 14 },
      watermark: { enabled: true, text: "SAMPLE PAPER", opacity: 0.07, fontSize: 50, rotation: -45 },
    },
    defaultInstructions: [],
    sectionStructure: [
      { title: "SECTION 1 - SINGLE CORRECT CHOICE", instructions: "Mark only one correct option. (+4 / -1 Marks)", defaultQuestionType: "mcq", defaultMarksPerQuestion: 4, questionCount: 20 },
      { title: "SECTION 2 - NUMERICAL VALUE TYPE", instructions: "Enter the correct numerical value rounded to two decimals. (+4 / 0 Marks)", defaultQuestionType: "numerical", defaultMarksPerQuestion: 4, questionCount: 5 },
    ],
  },
];
